# Distance and robot parameters
ARM_MOTOR_SPEED = 400
ARM_MOTOR_SPEED_FAST = 1000

WHEEL_DIAMETER = 92
AXLE_TRACK = 130
CIRCUMFERENCE = 3.14 * WHEEL_DIAMETER

# Drive speeds
DRIVE_SPEED_FAST = 400
DRIVE_SPEED_NORMAL = 200
DRIVE_SPEED_SLOW = 50

# Turn speeds
TURN_RATE = 150
TURN_THRESHOLD = 5

# Color sensor thresholds
BLACK_THRESHOLD = 10
WHITE_THRESHOLD = 90

